# Generated by Django 3.2.5 on 2021-08-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInfo',
            fields=[
                ('referral_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('dob', models.DateField()),
                ('exp', models.IntegerField()),
                ('Grad', models.TextField(max_length=100)),
                ('resume_att', models.FileField(upload_to='resume_docs/%Y/%m/%d/')),
                ('domain', models.CharField(max_length=30)),
                ('score_percent', models.CharField(max_length=30)),
                ('college_name', models.CharField(max_length=100)),
                ('grad_year', models.IntegerField()),
                ('State', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
