# Generated by Django 3.2.5 on 2021-08-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateinfo',
            name='referral_id',
        ),
        migrations.AddField(
            model_name='candidateinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
